ad: main.o  prime_b.o prime_d.o
	f95 -o ad main.o prime_b.o prime_d.o 

	



main.o: main.f95
	f95 -c main.f95

prime_b.o: prime_b.f95
	f95 -c prime_b.f95

prime_d.o: prime_d.f95
	f95 -c prime_d.f95



	    
	
		

clean:

	rm -rf *.o ad
	


	
