!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.9 (r5096) - 24 Feb 2014 16:53
!
!  Differentiation of prime in reverse (adjoint) mode (with options i4 dr8 r4):
!   gradient     of useful results: f
!   with respect to varying inputs: f x1 x2
!   RW status of diff variables: f:in-zero x1:out x2:out
SUBROUTINE PRIME_B(x1, x1b, x2, x2b, f, fb)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: x1, x2
  DOUBLE PRECISION :: x1b, x2b
  DOUBLE PRECISION :: f
  DOUBLE PRECISION :: fb
  x1b = (2*x2+3*x1**2)*fb
  x2b = (2*x1+4*x2**3)*fb
  fb = 0.D0
END SUBROUTINE PRIME_B
