!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.9 (r5096) - 24 Feb 2014 16:53
!
!  Differentiation of prime in forward (tangent) mode (with options i4 dr8 r4):
!   variations   of useful results: f
!   with respect to varying inputs: x1 x2
!   RW status of diff variables: f:out x1:in x2:in
SUBROUTINE PRIME_D(x1, x1d, x2, x2d, f, fd)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: x1, x2
  DOUBLE PRECISION, INTENT(IN) :: x1d, x2d
  DOUBLE PRECISION, INTENT(OUT) :: f
  DOUBLE PRECISION, INTENT(OUT) :: fd
  fd = 3*x1**2*x1d + 4*x2**3*x2d + 2*(x1d*x2) + 2*(x1*x2d)
  f = x1**3 + x2**4 + 2*x1*x2
END SUBROUTINE PRIME_D
