!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.9 (r5096) - 24 Feb 2014 16:53
!
SUBROUTINE MAIN_CD()
  USE GLOB_D
  IMPLICIT NONE
  TYPE(SOLN) :: s
  READ(*, *) s%x, s%y, s%z
  CALL SOLVER(func, s)
  PRINT*, func
END SUBROUTINE MAIN_CD
